version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
    networks:
      - backend

  server:
    container_name: digital-shift
    build: .
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "80:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge