// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"eh-digital-shift/config"
	"eh-digital-shift/httpServer"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func Initialize() (*httpServer.Server, error) {
	echoEcho := echo.New()
	configConfig := config.NewConfig()
	mongoServiceInterface := mongoServiceProvider(configConfig)
	bookingANumberUseCase := bookingANumberProvider(mongoServiceInterface)
	listBookingUseCase := bookingListProvider(mongoServiceInterface)
	bookingInterface := bookingHandlerProvider(bookingANumberUseCase, listBookingUseCase)
	app := appProvider(bookingInterface)
	server := serverProvider(echoEcho, configConfig, app)
	return server, nil
}
